# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Movies', 'Movies')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.TextField()),
                ('image_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='nothing', upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Category')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.CharField(choices=[('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Eldoret', 'Eldoret')], max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Location'),
        ),
    ]
